### ISSUE TITLE
No module named 'pyDeepInsight.image_transformer'

### ISSUE THREAD

**Issue by ClassifierPower** [shangruJia/scDeepInsight#3]
I am following the tutorial you gave to annotate the cells of the sample data, but I am executing the command pbmc.ImageTransform("sample.h5ad", "barcode.csv", "image.npy") to convert the RNA data into an image. , an error is always reported, and the error message is ModuleNotFoundError: No module named 'pyDeepInsight.image_transformer'. This error occurs when reading the file. Can you give me some help? Many thanks.

**Comment by Drbuilders** [comment]
Thank you for your comment! 
The package [pyDeepInsight](https://github.com/alok-ai-lab/pyDeepInsight) also needs to be installed additionally. This dependency has not been published to PyPI and will not be installed automatically.
You can install it through:
`python3 -m pip -q install git+https://github.com/alok-ai-lab/pyDeepInsight.git#egg=pyDeepInsight`
Some other details are described in the [PyPI page](https://pypi.org/project/scdeepinsight/)
If there are still any problems, please let me know.

**Comment by BettenWhite** [comment]
In fact, I have already installed pyDeepInsight, but the code still reports the above error. Specifically：
`Traceback (most recent call last):
  File "D:\tobebetter\Best_practices\pyscd\test.py", line 9, in <module>
    pbmc.ImageTransform(query_path, barcode_path, image_path)
  File "D:\miniconda3\envs\scD\lib\site-packages\scdeepinsight\pbmc.py", line 58, in ImageTransform
    it = pickle.load(file)
ModuleNotFoundError: No module named 'pyDeepInsight.image_transformer'
`
Is the problem caused by img_transformer_pbmc.obj ?

**Comment by shangruJia** [comment]
I have tested the code in the tutorial for image conversion and annotation on different OS (Ubuntu 20.04.5, Windows 11, macOS 14.0), and they all work fine. I cannot reproduce the error currently, the 'img_transformer_pbmc.obj' seems not to be the reason for the error.

Could you please try reinstalling pyDeepInsight and scDeepInsight packages to test whether this error still exists? To avoid possible name duplication issues, please use "pip list" to check whether the correct packages have been installed. Especially for pyDeepInsight, please install from Github repostitory through `python3 -m pip -q install git+https://github.com/alok-ai-lab/pyDeepInsight.git#egg=pyDeepInsight` rather than `pip install pyDeepInsight`

If this error still exists, please inform me.
